# Generated by Django 4.0 on 2024-04-05 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=150, verbose_name='program or project name')),
                ('slug', models.SlugField(max_length=200)),
                ('year', models.PositiveIntegerField(max_length=5)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='data/year/department/program/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='main.department')),
            ],
            options={
                'ordering': ('-date_uploaded',),
            },
        ),
    ]
