# Generated by Django 4.0 on 2024-04-23 08:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('date_uploaded',)},
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='file',
            field=models.FileField(upload_to=main.models.program_file_path),
        ),
        migrations.AlterField(
            model_name='program',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
